version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8000"
    command: "uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./dist:/usr/src/code/dist
      - ./db.sqlite:/usr/src/code/db.sqlite
