name: Run Unit Test via Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: r.txt
        run: |
          python -m pip install --upgrade pip
          if [ -f r.txt ]; then pip install -r r.txt; fi

      - name: Ruff
        run: |
          pip install ruff
          ruff .
        continue-on-error: true

      - name: pytest
        run: |
          pytest -v -s
